apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wwxujh9k1-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:a37b0503c6cde5b6b1d4aac5b396840b6ec730f1@sha256:7696d3bce8feb18560cc2972babc5a8e68eb69563b7877db2b1b81effcae78a7
          name: container-image
